### ISSUE TITLE
CPT fails with exception on Ubuntu 16.04.1 LTS

### ISSUE THREAD

**Issue by hacst** [vgvassilev/cling#109]
Following the build instructions at https://github.com/vgvassilev/cling#building-from-source-with-cling-packaging-tool fails for me on Ubuntu 16.04.1 LTS. I get:
```
$ ./cpt.py --check-requirements && ./cpt.py --create-dev-env Debug --with-workdir=./cling-build/
Traceback (most recent call last):
  File "./cpt.py", line 1750, in <module>
    if args['current_dev'].startswith('branch:'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by vgvassilev** [comment]
This is a recent regression could you add `--current-dev=tar`. @marsupial could you have a look, IIRC --current-dev was optional.

**Comment by marsupial** [comment]
I've added the fix to https://github.com/root-mirror/cling/pull/50

**Comment by vgvassilev** [comment]
This should be fixed now. Thanks for reporting it to us!
