### ISSUE TITLE
Blocking points to have a conda package for cling and the cling kernel

### ISSUE THREAD

**Issue by SylvainCorlay** [vgvassilev/cling#112]
I put together a conda recipe for `cling` that is simply pulling the binary from your nighly build and was just enough to make the following binder work:

http://mybinder.org/repo/SylvainCorlay/cling-binder

(Just click on it to get a C++ Jupyter notebook from anywhere.)

As I was doing this, I came across a few pitfalls that would need to be solved for a cling recipe to be made available in an official conda channel like `conda-forge`.
1. The binaries are different on multiple flavors of linux64 (e.g. ubundu 14 vs ubuntu 16). I presume that this is due to the ABI compatibility breakage of gcc between 4.x and 5.x.
   
   Since build time is long, it might be too long for conda-forge.

2. The cling kernel, which is a python module should probably be in a different package, and have a dependency. Otherwise, this makes cling dependent on notebook and all its dependencies, which is a bit silly if you only want the interpreter.
   
   The proposal is to have two packages:
   - `cling`: only the interpreter
   - `jupyter-cling`: only the kernel, depends on the former.

3. Oddly, clangs comes along with some python which is not Python 3 compatible https://github.com/llvm-mirror/clang/pull/19 We will probably need to have this fixed for it to work on python-3 based anaconda installs.

4. Can we specify options for the cling interpreter launched by the cling-kernel? Such as
   - `-std=c++14`
   - include directories.

**Comment by SylvainCorlay** [comment]
^ @karies @vgvassilev

**Comment by vgvassilev** [comment]
@SylvainCorlay thanks for opening this meta issue.

1. The ABI issue was solved and we backported the patch. We see another set of ABI issues (I think 1 or 2). This is only one of the reasons we have different builds for different linux platforms. Another problem for instance is that llvm link against `libtinfo` for colored diagnostics. See discussion #96. Once we solve this, we could solve this.

2. That makes sense but we don't have a person to do it. I'd be happy to review a PR for splitting this!

3. Could you put this PR at https://reviews.llvm.org/ add the people implemented the code as reviewers (git blame should help) and add me and cfe-commits as subscribers. This should get you on the fast track to get this change in clang's mainline.

4. Yes, you could specify languages and other options in the same manner as to clang. Eg. `cling -std=c++14` should give you c++ 14 mode of cling.

**Comment by SylvainCorlay** [comment]
> 2. That makes sense but we don't have a person to do it. I'd be happy to review a PR for splitting this!

Thanks. Expect a patch from me in the next week!

>  Could you put this PR at https://reviews.llvm.org/ add the people implemented the code as reviewers (git blame should help) and add me and cfe-commits as subscribers. This should get you on the fast track to get this change in clang's mainline.

Will do.

> Yes, you could specify languages and other options in the same manner as to clang. Eg. cling -std=c++14 should give you c++ 14 mode of cling.

How do I pass options in the case of the kernel?

**Comment by vgvassilev** [comment]
I don't know but I believe you can find this information here https://github.com/root-mirror/root/tree/master/bindings/pyroot/

**Comment by SylvainCorlay** [comment]
> > Could you put this PR at https://reviews.llvm.org/ add the people implemented the code as reviewers (git blame should help) and add me and cfe-commits as subscribers. This should get you on the fast track to get this change in clang's mainline.

> Will do.

Turns out a few people already proposed patches to fix this but it has not been acted upon yet.

**Comment by vgvassilev** [comment]
Could you give me the pointers and I will try to ask somebody to review.

**Comment by SylvainCorlay** [comment]
I came across

- https://reviews.llvm.org/D20785
- https://reviews.llvm.org/D7842

I added a comment in the first issue, which is the most recent, asking the author to also correct other syntax that only works with legacy python 2.

For your reference, the diff from my other PR is https://github.com/llvm-mirror/clang/pull/19/files.

**Comment by SylvainCorlay** [comment]
Thanks for pushing on the Python 3 compat issues of LLVM!

**Comment by vgvassilev** [comment]
It seems resolved. Does it work for you?

**Comment by SylvainCorlay** [comment]
I saw some activity on the issues, but it is not fixed. The python `print` and `except` statements are still python 2 only.

**Comment by vgvassilev** [comment]
Can I see which repository you are using. It is fixed in llvm's trunk.

**Comment by SylvainCorlay** [comment]
I am looking at the `llvm-mirror` org https://github.com/llvm-mirror/clang

**Comment by vgvassilev** [comment]
Can you point me to the files you have in mind.

**Comment by vgvassilev** [comment]
Ah, the part I was missing is that closed patches were not addressing all of the issues of https://github.com/llvm-mirror/clang/pull/19/files. Could you submit that PR for review there?

**Comment by SylvainCorlay** [comment]
It seems some of it was just updated... Although there are outstanding `print` statements here: https://github.com/llvm-mirror/clang/blob/master/tools/scan-view/share/ScanView.py

**Comment by SylvainCorlay** [comment]
> Ah, the part I was missing is that closed patches were not addressing all of the issues of https://github.com/llvm-mirror/clang/pull/19/files. Could you submit that PR for review there?

Yes, although I will be travelling this afternoon...

**Comment by vgvassilev** [comment]
No worries, just add the right reviewers and I will check it it, once it is greenlit.

**Comment by SylvainCorlay** [comment]
I wonder if the cling kernel should have the sys-prefix's include directory as one of the include directories.

If yes, I guess we would have the usual precedence order:

`system (/usr/include)` < `sys-prefix (&PREFIX/include)` < `user (.local/include)`...

**Comment by vgvassilev** [comment]
What &PREFIX resolves to?

**Comment by SylvainCorlay** [comment]
It resolves to the installation directory of anaconda.

When running in a conda environment, it resolves to the conda environment's sys-prefix.

**Comment by vgvassilev** [comment]
If it is specific to the conda environment I'd suggest to pass an option to the kernel, wouldn't that work?

**Comment by SylvainCorlay** [comment]
Just thinking out loud wrt the prefix.  The question remains on the user and system include directories.

**Comment by vgvassilev** [comment]
@SylvainCorlay I wanted to ping you on the python related patches for review.

**Comment by SylvainCorlay** [comment]
Sorry, I was swamped today. I will get back into this tonight and respond on the subject of traitlets too.

**Comment by vgvassilev** [comment]
ping... is this still of interest?

**Comment by SylvainCorlay** [comment]
Yes, I will be getting back to this later with some more material for the cling folks.

**Comment by SylvainCorlay** [comment]
I have started working on packaging cling for `conda-forge`.

Conda can package multiple incompatible flavors of the same package (same name and version number) with something called "features". Features are a property of the environment.

The idea is that when installing `cling`, you would enable the `cling-patches` feature which would install the `cling-patches` versions of llvm and clang.

PRs to the llvm and clang recipes are 

    https://github.com/conda-forge/llvmdev-feedstock/pull/4
    https://github.com/conda-forge/clangdev-feedstock/pull/1

Then we will be able to add a cling recipe to the conda-forge channel, and anyone will be able to install cling with the conda package manager by typing `conda install -c conda-forge cling`

**Comment by SylvainCorlay** [comment]
The patch are being applied to the source trees of llvm and the clang at the point version that is being pulled by the recipe, respectively

 - llvm 3.9.0
 - clang 3.8.1

However, it seems that the cling-patches addition cannot apply on the top of clang 3.8.1. It would be really helpful for me to know which version of clang to use to add these patches.

**Comment by SylvainCorlay** [comment]
Ping @vgvassilev @karies on the above comment.

**Comment by vgvassilev** [comment]
Thanks for the work. Is there something we need to do on our side?

**Comment by SylvainCorlay** [comment]
I have one question: for the clang recipe, it does not seem that the cling-patches which I took from where master is at can apply on the to of 3.9.1.

**Comment by vgvassilev** [comment]
Our patches are based on a specific revision of LLVM, we generally do not sync when there is a new version out. Which clang-patches are you using? `https://root.cern.ch/gitweb/?p=clang.git` and `https://root.cern.ch/gitweb/?p=llvm.git` are the repos which contain the most recent ones.

**Comment by vgvassilev** [comment]
FWIW, we are planning to merge as many patches as possible in upstream LLVM/clang. I start doing that soon.

**Comment by SylvainCorlay** [comment]
I created patch files for each commit in your forks of llvm and clang that are not in master. Then I try to apply them to llvm 3.9.1 and clang 3.9.1 which are very recent releases (from December).

 - The application of the patches is succesful for llvm (https://github.com/conda-forge/llvmdev-feedstock/pull/4)
 - There are more patches (over 50) for clang https://github.com/conda-forge/clangdev-feedstock/pull/1

**Comment by vgvassilev** [comment]
Ok, I cannot look at them right now, but I do not expect all 50 to fail to apply. Perhaps only a minimal set of them need to be fixed.

**Comment by SylvainCorlay** [comment]
May be I was not clear, but it is succesfull for the first 49!

**Comment by SylvainCorlay** [comment]
There might be a commit from master that I should took too which will fix everything. That could be cleaner than trying to amend the patches.

**Comment by vgvassilev** [comment]
Ah, ok, good. The `0050-Survive-auto-types-in-DeclPrinter.patch` was put upsteam. So we do not need it.

**Comment by SylvainCorlay** [comment]
Gotcha, 3.9.1 is more recent than where you branched out.

**Comment by SylvainCorlay** [comment]
All patches apply now thanks! :+1:

**Comment by SylvainCorlay** [comment]
@vgvassilev I am looking at it again. Would you guys consider cutting a 0.4 version of cling or should I package 0.3?

**Comment by vgvassilev** [comment]
We can cut if it is necessary. There are a few improvements. I am quite busy now, it has to be in 2-3 weeks if you want v0.4. Let me know.

**Comment by SylvainCorlay** [comment]
@vgvassilev thanks, I am attempting the full build from the conda recipes. We will see if I need a more recent version. Otherwise I will simply require a specific commit of cling for now.

**Comment by SylvainCorlay** [comment]
Although a release with the latest updates to the kernel would be nice!

**Comment by SylvainCorlay** [comment]
Despite of the major TravisCI outage of this week, some progress was made: the `cling-patches` meta package was merged into conda-forge and the patched `llvmdev` package is now going through.

When it comes to the patched clang package, the following problem occurs: two of the clang patches that move files:

```
0009-Make-clang-Parse-RAIIObjectsForParser.h-public.patch
0010-Forward-to-new-location.patch
```

These patch files are generated from the cling-patches branch, rebased on the 0.3.9 release, with `git format-patch release_39`, which works perfectly.

The problem is that the `tar.gz` of the source used by conda to build the package is not a git repo but only a snapshot of the sources. In this case, conda-build applies the patches with unix's `patch` command, which is compatible with git **except** when files are moved or deleted....

**Comment by SylvainCorlay** [comment]
@vgvassilev OK, that issue is solved.

I think that the only thing delaying the cling variants of llvm and clang to get in conda-forge is the Travis CI build backlog.

I would love to see a new version of cling tagged so that I can include the latest changes related to kernel specs.

**Comment by SylvainCorlay** [comment]
Just that having a conda installable cling is likely to increase adoption of the jupyter kernel, and changing the name from `C++` to` C++[11 | 14 | 17]` is a breaking change for notebooks.

**Comment by vgvassilev** [comment]
Thanks for the work! I will tag, but probably in couple of days. I need to sync this and prepare a release.

**Comment by SylvainCorlay** [comment]
A couple of days is probably what is needed to go through the OS X build backlog anyway, so we should be good.

**Comment by vgvassilev** [comment]
@SylvainCorlay, ok, we should be very explicit there and say that we do not guarantee backward compatibility at least in the beginning.

**Comment by SylvainCorlay** [comment]
No problem. FYI, in the hand-made conda package that we use for the xtensor demo here quantstack.net/xtensor we are already using the newer `C++14` kernel language name.

**Comment by SylvainCorlay** [comment]
@vgvassilev quick note on the 0.4 release of cling: it would be great if the `cling-patches` branches of llvm and clang were rebased on `3.9.1` so that the conda packaged version of cling is the same as yours.

In general, having the patches applied to an actual release will help packaging.

**Comment by SylvainCorlay** [comment]
FYI: everything seems to work now for the conda packaging of the cling variant llvm and clang. I am fighting with circleci so that the build of the two variants for clang remains under 120min cap on the docker image.

**Comment by SylvainCorlay** [comment]
> FWIW, we are planning to merge as many patches as possible in upstream LLVM/clang. I start doing that soon.

On the subject of getting these patches upstream, llvm seems to be a lower hanging fruit than clang. It would also be the most useful because very few packages have a *runtime* dependency on clang while many have one on llvm (JuliaLang, Numba). So if you get the llvm patches in, we will be able to have cling installed in the same environment as Julia and Numba without any issue.

**Comment by vgvassilev** [comment]
Indeed, this is our first step.

**Comment by SylvainCorlay** [comment]
FYI, cling variants of llvm and clang are on conda-forge for all platforms. All I need now is a 0.4 tag for cling!

**Comment by vgvassilev** [comment]
Thanks for all the efforts you put in this!

**Comment by SylvainCorlay** [comment]
@vgvassilev it all works now. The conda package should be up in a few hours.

**Comment by SylvainCorlay** [comment]
FYI, the conda package works well and we can use the cling interpreter.

There are issues with the kernel itself which I think are not `build / packaging /  installation` issue but legitimate issues in how the cling kernel works.

**Comment by SylvainCorlay** [comment]
@vgvassilev FYI, on each IO operation (i.e. std::out) our msvc build yields

`Cleanup funclets for the MSVC++ personality cannot contain exceptional actions`.

Is there a compiler flag we should be using for windows that would prevent this?

**Comment by vgvassilev** [comment]
Currently, windows is unsupported. I am not aware of a fix for this issue.

**Comment by vgvassilev** [comment]
I know, we are working on this. We have a few remaining tests failing exactly wrt exception handling.

**Comment by SylvainCorlay** [comment]
- The OS X build works.
- The Windows build has the above issue (`Cleanup funclets for the MSVC++ personality cannot contain exceptional actions`).
- I am struggling with glibc versions on conda-forge (bad packaging of gcc on conda) It is not related to cling.

**Comment by SylvainCorlay** [comment]
If you guys had a little bit of time for a skype / hangout meeting at some point, it would be great.

**Comment by vgvassilev** [comment]
Yeah, let's take this offline. Could you drop me an email?

**Comment by SylvainCorlay** [comment]
The cern one? https://github.com/vgvassilev/clad/blob/master/Credits.txt#L29

**Comment by vgvassilev** [comment]
Either works ;)

**Comment by SylvainCorlay** [comment]
thanks
