### ISSUE TITLE
Jupyter notebooks crash - unresolved symbol

### ISSUE THREAD

**Issue by erlanger** [vgvassilev/cling#114]
Hi, thanks for fixing issue #113. Unfortunately jupyter notebooks are still not working. The error is the following:

```C++
IncrementalExecutor::executeFunction: symbol 'cling_runtime_internal_throwIfInvalidPointer' 
unresolved while linking [cling interface function]!
```
Please try the attached notebook in jupyter and you will see the error. 
This is with cling commit fbd11 and jupyter 4.2.0

[clingnotebook.zip](https://github.com/vgvassilev/cling/files/532047/clingnotebook.zip)

NOTE: the code works fine from the command line cling, the error only shows in the jupyter notebook.

**Comment by vgvassilev** [comment]
It seems that the hash you pasted is missing one character.

Would you be able to narrow down the problem by simplifying the code? It'd be great if we started working on a notebook-based test suite.

**Comment by erlanger** [comment]
Here is a screenshot with much simpler code:

![clingjupyter-bug](https://cloud.githubusercontent.com/assets/8608855/19539972/5e59386c-962a-11e6-923a-969c4283208d.png)

**Comment by SylvainCorlay** [comment]
Thanks @erlanger this is exactly what I am seeing too. Although not specifically with pointers.

**Comment by SylvainCorlay** [comment]
@erlanger fyi in the case of a jupyter kernel, I see the following ABI compatibility issue warning:

https://github.com/root-mirror/cling/issues/29

but not with the regular cling interpreter itself.

**Comment by erlanger** [comment]
@SylvainCorlay I don't think it is related to the ABI compatibility warning, because I get unresolved symbol  error ***without*** the ABI compatibility warning.

**Comment by SylvainCorlay** [comment]
FYI the warning is diplayed in the console that launched the notebook server, not in the notebook.

**Comment by erlanger** [comment]
@SylvainCorlay Indeed, I checked the *jupyter console* (I knew the error does not appear in the notebook). There is ***no ABI warning*** in the jupyter console and I ***still get the unresolved symbol error***. The reason why I don't get the ABI warning is because everything in my computer was compiled with the same version of gcc and related libraries; including cling (which I compiled myself). So there is no chance of ABI mismatch.

**Comment by SylvainCorlay** [comment]
> @SylvainCorlay Indeed, I checked the jupyter console (I knew the error does not appear in the notebook). There is no ABI warning in the jupyter console and I still get the unresolved symbol error. The reason why I don't get the ABI warning is because everything in my computer was compiled with the same version of gcc and related libraries; including cling (which I compiled myself). So there is no chance of ABI mismatch.

Ok that clarifies it.

**Comment by SylvainCorlay** [comment]
FYI, I am not observing this on ubuntu 14 with the binaries meant for ubuntu 14.

**Comment by erlanger** [comment]
@SylvainCorlay , @vgvassilev I think this is the solution:

For some reason the  **`cling_runtime_internal_throwIfInvalidPointer`** symbol is not linked into `libclingJupyter.so` but it is linked into the main cling executable.  This is similar to what is mentioned in [Stackoverflow](https://stackoverflow.com/questions/5685617/missing-symbols-from-static-library-in-linked-executable#5687860). 

I made the following patch based on the solution mentioned and it works. Here is the patch.
Below I show the output of `nm` before and after the patch showing the patch works as intended.

# Patch
```
diff --git a/tools/Jupyter/CMakeLists.txt b/tools/Jupyter/CMakeLists.txt
index 7db7ae5..53ed0dc 100644
--- a/tools/Jupyter/CMakeLists.txt
+++ b/tools/Jupyter/CMakeLists.txt
@@ -26,7 +26,7 @@ set(LIBS

         clingUserInterface
         clingMetaProcessor
-        clingInterpreter
+        -Wl,--whole-archive clingInterpreter -Wl,--no-whole-archive
         clingUtils
     )
```
# Verification
Here is the output from `nm`:
```sh 
$ #before patch
$ nm  -BCD /opt/cling/lib/libclingJupyter.so  |grep IfInv
$ 
$ #after patch
$ nm  -BCD ./pkg/cling-git/opt/cling/lib/libclingJupyter.so  |grep IfInv
000000000072ab40 T cling_runtime_internal_throwIfInvalidPointer
$
```
I also tested it with Jupyter and it works fine.
The `ld` man page explains why this option works:

# ld man page
```
 --whole-archive
           For each archive mentioned on the command line after the --whole-archive option, include every object
           file in the archive in the link, rather than searching the archive for the required object files.  This
           is normally used to turn an archive file into a shared library, forcing every object to be included in
           the resulting shared library.  This option may be used more than once.

           Two notes when using this option from gcc: First, gcc doesn't know about this option, so you have to use
           -Wl,-whole-archive.  Second, don't forget to use -Wl,-no-whole-archive after your list of archives,
           because gcc will add its own list of archives to your link and you may not want this flag to affect those
           as well.

```

However it remains a mystery why the symbol is not included in the first place whereas other symbols are included. Perhaps it has to do with the fact that `lib/Interpreter/ExceptionRTTI.cpp` (which has the definition for the missing symbol)  is compiled with special options:  `--frtti` and `-fexceptions`.

Thanks for quickly responding to the issue, this is what gave me incentive to spend some time to solve the problem.

**Comment by vgvassilev** [comment]
I think we are not referencing this symbol and it gets optimized away by the linker. We have the same issue in cling, which we solve by 'artificial uses' of the symbol. Have a look here: https://github.com/vgvassilev/cling/blob/master/lib/Interpreter/RequiredSymbols.cpp We need something like this in the jupiter kernel, too.

**Comment by erlanger** [comment]
@vgvassilev, in my humble opinion it would be dangerous to apply this solution to the jupyter kernel. The kind of solution used in `RequiredSymbols.cpp` is useful if you are concerned about space optimization and know **at link time** what symbols will be needed. This is true for a binary executable, like the cling binary; but it is not true **for a shared library**. The Jupyter kernel is a shared library, and therefore I suggest that it be treated differently than the cling binary in this respect.

By definition we don't know **at link time** what symbols will be needed at runtime by callers to a shared library, and the kernel python code could presumably need any symbol from the shared library, but this is not known at link time. Using something like the kind of solution used in `RequiredSymbols.cpp` will simply open the possibility of hard to track future bugs which appear in the Jupyter kernel but not in the cling executable (which is exactly what we are seeing now). 

This is precisely why the linker provides the `--whole-archive` option, it is meant to be used with shared libraries.

What do you think?

**Comment by vgvassilev** [comment]
Good point! Would that work on Windows? Perhaps we need to have an export file?

**Comment by erlanger** [comment]
I have no idea, I don't even know if the bug shows up on Windows. You'll have to get a windows person on that.

**Comment by SylvainCorlay** [comment]
Thanks for tracking this down.

**Comment by erlanger** [comment]
you're welcome, thanks for all the work you've done.

**Comment by vgvassilev** [comment]
@erlanger could you open a pull request with this patch? There we could review and integrate it.

**Comment by erlanger** [comment]
Alright, it is PR #117

**Comment by vgvassilev** [comment]
Should be fixed now. Thanks for the report!
