### ISSUE TITLE
Link error with Jupyter kernel only

### ISSUE THREAD

**Issue by SylvainCorlay** [vgvassilev/cling#116]
I am seeing the following link error in certain cases but only when running as a Jupyter kernel, but not in the classical cling REPL:

```
IncrementalExecutor:: excuteFunction: symbol 'cling_runtime_internal_throwIfInvalidPointer' unresolved while linking function '_GLOBAL__sub_I_cling_module_2'!
```

**Comment by SylvainCorlay** [comment]
Seems related to https://github.com/root-mirror/cling/issues/11

ping @karies

**Comment by erlanger** [comment]
@SylvainCorlay this the same error I reported in #114, it is related to when you use a pointer: see the narrowed down test case in #114.

**Comment by SylvainCorlay** [comment]
Closing as a duplicate of #114.
