### ISSUE TITLE
Separate definition of `operator=()`?

### ISSUE THREAD

**Issue by dabro** [vgvassilev/cling#119]
I'm not sure if I'm doing something really silly, but I'm unable to define `operator=` outside of the class declaration:
```
class foo
{
public:
    foo() = default;
    foo& operator=(foo const &);
    foo clone(foo const &);
private:
    data * address;
};

foo foo::clone(foo const & other) 
{
    return foo(other);
}

foo& foo::operator=(foo const & other) 
{
    std::swap(address, other.address);
    return *this;
}
```
Constructors (not illustrated here) and methods not automatically defined by the compiler work fine.  However, for `operator=()` I get:
```
input_line_7:3:1: error: function definition is not allowed here
{
^
```
The method is not defined:
```
foo fa; //(foo &) @0x104c06000
foo fb = fa; //(foo &) @0x104c06150
foo fc; //(foo &) @0x104c06330
fc = fa; //IncrementalExecutor::executeFunction: symbol '_ZN3fooaSERKS_' unresolved 
         //while linking [cling interface function]!
         //You are probably missing the definition of foo::operator=(foo const&)
         //Maybe you need to load the corresponding shared library?
```

**Comment by vgvassilev** [comment]
Could you show us how `class foo` goes in cling? Do you `#include` it or you type it at the prompt?

**Comment by dabro** [comment]
I declared `foo` directly in cling, initially via Jupyter, but here you can see directly in console:
```
[cling]$ class bar {
[cling]$ ?   public:
[cling]$ ?   bar() = default;
[cling]$ ?   bar& operator=(bar const&);
[cling]$ ?   };
[cling]$ bar b;
[cling]$ .class bar
===========================================================================
class bar
SIZE: 1 FILE: input_line_5 LINE: 1
List of member variables --------------------------------------------------
List of member functions :---------------------------------------------------
filename     line:size busy function type and name
(compiled)     (NA):(NA) 0 public: bar();
(compiled)     (NA):(NA) 0 public: class bar &operator=(const class bar &);
[cling]$ bar& bar::operator=(bar const&) { return bar(); }
input_line_7:2:34: error: function definition is not allowed here
 bar& bar::operator=(bar const&) { return bar(); }
```

**Comment by vgvassilev** [comment]
Could you try with:
```
.rawInput 1
bar& bar::operator=(bar const&) { return bar(); }
.rawInput 0
```

Currently we cannot detect if you are to define a function/member function and thus we need to toggle between two different states.

**Comment by dabro** [comment]
OK, sweet.
That did it.  In Jupyter I had to separate the `.rawInput`'s into separate cells to see errors on the `operator=` definition.  I had tried `.rawInput` while troubleshooting before posting, but didn't include `[0/1]` -- my bad.
I'm a little confused on the different behavior between the ctors, the operators, and normal methods like my `clone` above?

**Comment by vgvassilev** [comment]
I am glad that fixes it.

Can you be more specific about the different behavior of ctors/operators and methods in cling.

**Comment by dabro** [comment]
First, thanks so much for the awesome response...the project and everything involved is awesome.  I think this will really contribute to C++ uptake, even though a lot of folk who develop with traditional tools can't really understand the value.  I noted the other day that Java 9 is coming with a built-in REPL, after the response they noted to Scala's REPL...

Concerning different behavior:
1.  ctors didn't require `.rawInput`
2. my custom `clone` method didn't either
3. `operator=` however did

This is a minimized example demonstrating all of the above:
```
class foo
{
public:
    foo();
    foo operator=(foo const &);
    //foo& operator=(foo const &);
    foo operator[](int);
    foo clone(foo const &);
private:
    data * address;
};
```
and then the out-of-line definitions:
```
foo foo::operator=(foo const&) { return foo(); } //doesn't work without .rawInput
```
```
foo foo::operator[](int) { return *this; } //same
```
foo foo::clone(foo const & other) { return foo(other); } //This works though!
```
and of course after your guidance/troubleshooting:
```
.rawInput 1
foo foo::operator=(foo const&) { return foo(); } //works
foo foo::operator[](int) { return *this; } //same
.rawInput 0

**Comment by vgvassilev** [comment]
I believe this is due to a deficiency in our [SourceNormalization](https://github.com/vgvassilev/cling/blob/master/lib/Utils/SourceNormalization.cpp) logic in `IsClassOrFunction`.

**Comment by vgvassilev** [comment]
I am working on a more generic solution allowing us to disambiguate better between function declarations and statements.
