### ISSUE TITLE
Proper lambda captures? [=] vs [&]

### ISSUE THREAD

**Issue by dabro** [vgvassilev/cling#120]
```
int a = 1;
auto j = [&]{int b = 1; return a+b;};
auto k = [=]{int b = 1; return a+b;};

j(); //2
k(); //2
a = 2;
j(); //3
k(); //should be 2, actually is 3
```
Am I missing something?

**Comment by dabro** [comment]
also,
```
int a = 1;
auto f = []{a = 4;}; //shouldn't compile; xcode error: "Variable 'a' cannot be implicitly captured in a
                               // lambda with no capture-default specified"
f();
a; //4?
```

**Comment by vgvassilev** [comment]
Ah, you are right. Thanks for reporting that. This seems wrong. Apparently, the bug is because we compile (almost) everything wrapped in a function and we extract the declarations out afterwards. It seems that during this extraction we break the semantics of lambdas as it differ when in functions and on the global scope.

**Comment by dabro** [comment]
Huh, I didn't realize capture only applies to automatic variables.  `&` and `=` don't seem to matter at all for globals, and for member functions, `=` captures `this` in C++14 (`*this` in C++17), so sufficient for mutating member variables.

So for the two examples above, if a is a global in cling, then all three captures (`[]`, `[=]`, and `[&]`) are behaving correctly...

**Comment by dabro** [comment]
From Xcode 8.1 with C++14:
```
int test_int = 0;

int main(int argc, char *argv[])
{
    //"normal" capture behavior with stack variables
    int a = 1;
    auto k = [=]{return a;};
    auto j = [&]{return a;};
    a = 3;
    j(); //  3
    k(); // 1

    //ok, now behavior with globals
    []{test_int = 3;}(); // test_int = 3!!
    [=]{test_int = 4;}(); // test_int = 4!!  also no error from missing `mutable` keyword
}
```
So below behavior by cling would be correct, assuming globals:
```
int a = 1;

auto j = [&]{return a;};
auto k = [=]{return a;};
auto l = []{return ++a;};
l() //2
l() //3
l() //4
k() //4
a = 2
j() //2
k() //2
l() //2
```

**Comment by dabro** [comment]
And the following seems to work properly on stack variables:
```
void test2()
{
    int a = 1;
    auto j = [&]{return a;};
    auto k = [=]{return a;};
    a = 2;
    std::cout << "a from CBR lambda: " << j() << "\n"; //a from CBR lambda: 2
    std::cout << "a from CBV lambda: " << k() << "\n";//a from CBR lambda: 1
}
