### ISSUE TITLE
Parser input from existing stream

### ISSUE THREAD

**Issue by maxstrax** [vgvassilev/cling#122]
Hello,

I was wondering on how best to integrate cling to an existing framework!
After scanning through the code I found the StreamReader class. I believe it would be a great entry point for any third party application to interface with cling. If we have the ability to pass an existing std::istream there, to provide input for the parser from the stream, essentially we could achieve tight control of the parser by the application. The stream passed could be a file stream (std::ifstream for stored scripts, or std::cin for capturing keyboard input or even a std::stringstream for manipulating the script from the third party application.

Although this is more of a suggestion, I am looking forward to hearing from you,
Marios

**Comment by vgvassilev** [comment]
Hi,

  Could this help you https://rawgit.com/vgvassilev/cling/master/www/index.html

  Essentially section "Embedding Cling" shows how to create an interpreter object and pass code in the form of strings to it.

  How that is different from your intended use?

**Comment by maxstrax** [comment]
Thank you very much, I will attempt the implementation and inform you of the results!

**Comment by maxstrax** [comment]
Thank you very much, I will attempt the implementation and inform you of the results!
