### ISSUE TITLE
pressing tab key after #def causes crash/dumps core

### ISSUE THREAD

**Issue by weegreenblobbie** [vgvassilev/cling#128]
Starting cling and typing "#def" followed by the tab key causes a crash:

    $ /tmp/cling_2017-01-27_ubuntu14/bin/cling 
    Warning in cling::IncrementalParser::CheckABICompatibility():
      Possible C++ standard library mismatch, compiled with __GLIBCXX__ '20150426'
      Extraction of runtime standard library version was: '20150623'
    
    ****************** CLING ******************
    * Type C++ code and press enter to run it *
    *             Type .q to exit             *
    *******************************************
    [cling]$ #def#0 0x00000000008b2b65 llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8b2b65)
    #1 0x00000000008b0d1e llvm::sys::RunSignalHandlers() (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8b0d1e)
    #2 0x00000000008b0e5a SignalHandler(int) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8b0e5a)
    #3 0x00007f2242caecb0 (/lib/x86_64-linux-gnu/libc.so.6+0x36cb0)
    #4 0x000000000082dbeb cling::IncrementalParser::ParseInternal(llvm::StringRef) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x82dbeb)
    #5 0x000000000082f25c cling::IncrementalParser::Compile(llvm::StringRef, cling::CompilationOptions const&) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x82f25c)
    #6 0x00000000008332fe cling::Interpreter::CodeCompleteInternal(std::string const&, unsigned int) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8332fe)
    #7 0x0000000000835a89 cling::Interpreter::codeComplete(std::string const&, unsigned long&, std::vector<std::string, std::allocator<std::string> >&) const (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x835a89)
    #8 0x00000000008b8750 (anonymous namespace)::UITabCompletion::Complete(textinput::Text&, unsigned long&, textinput::EditorRange&, std::vector<std::string, std::allocator<std::string> >&) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8b8750)
    #9 0x00000000008bb40c textinput::Editor::ProcessCommand(textinput::Editor::ECommandID, textinput::EditorRange&) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8bb40c)
    #10 0x00000000008c48fa textinput::TextInput::ProcessNewInput(textinput::InputData const&, textinput::EditorRange&) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8c48fa)
    #11 0x00000000008c4c00 textinput::TextInput::ReadInput() (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8c4c00)
    #12 0x00000000008b8bd0 cling::UserInterface::runInteractively(bool) (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x8b8bd0)
    #13 0x0000000000783ddc main (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x783ddc)
    #14 0x00007f2242c99f45 __libc_start_main /build/eglibc-oGUzwX/eglibc-2.19/csu/libc-start.c:321:0
    #15 0x00000000007aee7d _start (/tmp/cling_2017-01-27_ubuntu14/bin/cling+0x7aee7d)
    Stack dump:
    0.	Program arguments: /tmp/cling_2017-01-27_ubuntu14/bin/cling 
    Segmentation fault (core dumped)

**Comment by drvink** [comment]
The most recent cling crashes for me on this too, even with just `.q`<kbd>TAB</kbd>.

**Comment by francoisbecker** [comment]
I third that

**Comment by vgvassilev** [comment]
Can you retry with the current master?
