### ISSUE TITLE
.file command

### ISSUE THREAD

**Issue by gouarin** [vgvassilev/cling#153]
It should be great to have the `.file` command like in IPython with `%%file` in Jupyter notebook.

I don't know if it is really difficult to implement but if you have some ideas of how to do that, tell me and I can try.

**Comment by gouarin** [comment]
Finally, we will do that in https://github.com/QuantStack/xeus-cling.

**Comment by vgvassilev** [comment]
Sorry for being late but I am a little busy. I would expect cling redirects help with that.

**Comment by gouarin** [comment]
@vgvassilev, I am sorry but I don't understand exactly what you mean...

**Comment by vgvassilev** [comment]
Wouldn't something like [that](https://github.com/vgvassilev/cling/blob/master/test/Prompt/OutputRedirect.C) help with what you want as behavior for simulating `%%file`.

**Comment by gouarin** [comment]
I think that it would be more easy to be able to implement magic function on xeus-cling side or xeus-magics package because it is very specific of the Jupyter kernel usage and not of cling. 

The idea of use `%%file` is to be able to compile the code with shell command using `!`.

**Comment by vgvassilev** [comment]
Ok, got it. Btw, cling also supports shebangs (look in the test suite).
