### ISSUE TITLE
Building packages for Debian fails

### ISSUE THREAD

**Issue by Trophime** [vgvassilev/cling#163]
Hi,
trying to build packages for debian with latest cling with:
```
./cpt.py --last-stable=deb
```
ends up with:
```
┌──────────────────────────────────────────────────────────────────────────────┐
│ Filtering Cling's libraries and binaries                                     │
└──────────────────────────────────────────────────────────────────────────────┘
regex_filename= /home/LNCMI-G/trophime/ci/build/cling-src/tools/cling/tools/packaging/dist-files.txt
Traceback (most recent call last):
  File "./cpt.py", line 2066, in <module>
    install_prefix()
  File "./cpt.py", line 566, in install_prefix
    dfile = open(regex_filename) 
IOError: [Errno 2] No such file or directory: '/home/LNCMI-G/trophime/ci/build/cling-src/tools/cling/tools/packaging/dist-files.txt'
```

Actually there is no .txt file but rather a .json file.
Would replacing the false filename with the right one simply fix this issue?

Best

**Comment by vgvassilev** [comment]
Sorry for the late reply. Replacing with the json should work.

**Comment by vgvassilev** [comment]
This happened because 35306f3f376ca6ff2487703e31034f4ace759c9d changed the json to txt. You probably downloaded the cpt.py from the master while the last stable version did not have that change. That should be fixed if you rerun the script because recently we released a new version of cling.
