### ISSUE TITLE
Wrong type string underlying value printer

### ISSUE THREAD

**Issue by SylvainCorlay** [vgvassilev/cling#180]
Here is a minimal reproducer in cling:

1) Define `base` and `Derived`:

```cpp
namespace b {

    class base {};

    template <class B>
    class Derived : public B
    {
    
    };
    
    using Foo = Derived<base>;
}
```

2) Instantiate an instance of `Foo` and display it:

```cpp
[cling]$ b::Foo foo;
[cling]$ foo
(b::Foo &) @0x10d0110c8
```

3) Make a copy of `foo` with an explicit type, and display it:

```cpp
[cling]$ b::Foo baz = foo;
[cling]$ baz
(b::Foo &) @0x10d011240
```

4) Make another copy of `foo` with the `auto` specifier, and try displaying it:

```cpp
[cling]$ auto bar = foo;
[cling]$ bar
input_line_14:2:33: error: unknown type name 'base'; did you mean 'b::base'?
 cling::printValue(*(b::Derived<base>**)0x7fff567dcdc0);
                                ^~~~
                                b::base
input_line_3:2:11: note: 'b::base' declared here
    class base {};
          ^
ERROR in cling's callPrintValue(): cannot pass value!
(b::Derived<base> &) ERROR in cling's callPrintValue(): missing value string.
```

The error seems to be in the `getTypeString` which misses the namespace specifier for the base class.

**Comment by vgvassilev** [comment]
@SylvainCorlay thanks for the report. It should be fixed in 01dbb6d9d523675694da95927eace14535c3040f

**Comment by SylvainCorlay** [comment]
It seems that the latest clang has a version of `getFullyQualifiedName` that provides the correct value.

**Comment by vgvassilev** [comment]
Forget to say. I am working on it. I will have a look. It is a bug in the way clang prints elaborated types.

**Comment by SylvainCorlay** [comment]
Thanks!

**Comment by SylvainCorlay** [comment]
Do you know of a workaround that we could use for this?

**Comment by vgvassilev** [comment]
I am not aware of any way to workaround it. It is a bug in clang's type printer which I am hunting down.

**Comment by SylvainCorlay** [comment]
The clang value printer in trunk appears to be quite different from this one. It might solved upstream.

**Comment by vgvassilev** [comment]
I suspect the issue is coming from [here](https://github.com/llvm-mirror/clang/blob/372df097866f776c2f1e232733f9db39bdabcfaf/lib/AST/TypePrinter.cpp#L1209). The RAII object resets the scope printing [here](https://github.com/llvm-mirror/clang/blob/372df097866f776c2f1e232733f9db39bdabcfaf/lib/AST/TypePrinter.cpp#L93). I am trying to reproduce this behavior will proper clang. So far unsuccessfully.

**Comment by SylvainCorlay** [comment]
Closing and reopening in root-mirror.

**Comment by vgvassilev** [comment]
That should be fixed now.

**Comment by SylvainCorlay** [comment]
> That should be fixed now.

Thanks! 

Is the following patch sufficient?

```diff
+    // Strip deduced types.
+    if (const AutoType* AutoTy = dyn_cast<AutoType>(QT.getTypePtr())) {
+      if (!AutoTy->getDeducedType().isNull())
+        return GetFullyQualifiedType(AutoTy->getDeducedType(), Ctx);
+    }
+
```

**Comment by SylvainCorlay** [comment]
Do you know if it fixes the case of template template parameters?

```cpp
namespace b {

    template <class T>
    class Foo
    {
    };

    template <template <class> class T>
    class Bar
    {
    };
    
    using Baz = Bar<Foo>;
}

auto h = std::vector<b::Baz>();
h
```
