### ISSUE TITLE
Improve exception safety with smart pointers

### ISSUE THREAD

**Issue by elfring** [vgvassilev/cling#52]
Would you like to wrap any pointer data members with the template class "[std::unique_ptr](http://en.wikipedia.org/wiki/Smart_pointer#unique_ptr "a smart pointer")"?

Update candidates:
* [TerminalConfigUnix](https://github.com/vgvassilev/cling/blob/90abfb5485b5386d164a9ca9b1cfccbb5b795a6a/lib/UserInterface/textinput/TerminalConfigUnix.cpp#L56 "TerminalConfigUnix class")
* [TextInput](https://github.com/vgvassilev/cling/blob/90abfb5485b5386d164a9ca9b1cfccbb5b795a6a/lib/UserInterface/textinput/TextInput.cpp#L32 "TextInput class")
* [TextInputContext](https://github.com/vgvassilev/cling/blob/bef24f727cc91426882052e910d9fb7b960a4e5a/lib/UserInterface/textinput/TextInputContext.h#L34 "TextInputContext class")

**Comment by vgvassilev** [comment]
Closing, tagged as not important, thus not enough manpower to do the transformation.
