### ISSUE TITLE
New Error

### ISSUE THREAD

**Issue by martell** [vgvassilev/cling#64]
Hi @vgvassilev,

I have a new error that I never had when I last built a few months ago.

``
In file included from llvm/tools/cling/lib/Interpreter/ValuePrinter.cpp:10:0: llvm/tools/cling/lib/Interpreter/../../include/cling/Interpreter/Value.h: In instantiation of 'static T cling::Value::CastFwd<T>::cast(const cling::Value&) [with T = long double]':
llvm/tools/cling/lib/Interpreter/../../include/cling/Interpreter/Value.h:209:36: required from 'T cling::Value::simplisticCastAs() const [with T = long double]'
llvm/tools/cling/lib/Interpreter/ValuePrinter.cpp:213:48: required from here
llvm/tools/cling/lib/Interpreter/../../include/cling/Interpreter/Value.h:104:53: 
error: cast from 'void*' to 'long unsigned int' loses precision [-fpermissive]
           return (T) (unsigned long) V.getAs<void*>();
``

Seems like the header is wrong ?

Why is this cast from 'void*' to 'long unsigned int' 
include/cling/Interpreter/Value.h:104:53: 
return (T) (unsigned long) V.getAs<void*>();

Should this not be size_t and not unsigned long ?

**Comment by vgvassilev** [comment]
Should be fixed now! Thanks!
