### ISSUE TITLE
Binary snapshot not running on Ubuntu

### ISSUE THREAD

**Issue by nesteruk** [vgvassilev/cling#66]
Downloaded binary snapshot and got this:

<img src="http://i.imgur.com/Z97SkWo.png"/>

**Comment by vgvassilev** [comment]
It tells you that you don't have libc++ installed. Are you sure you have it on your system?

**Comment by nesteruk** [comment]
I did have `libc++` installed, but apparently I needed to install `g++` as well for it all to work. This is strange because I thought Cling was essentially self-contained.

**Comment by vgvassilev** [comment]
Well, yes, this is the way how cling resolves source file locations.
