### ISSUE TITLE
Making use of the compilation database

### ISSUE THREAD

**Issue by mcraveiro** [vgvassilev/cling#67]
Many thanks for a very useful project. This is more of a question than a issue. Does Cling support the compilation database? It would be great if one could load up a compilation database for a given project, and then be able to include any of the files on that project and use them from cling.

**Comment by vgvassilev** [comment]
Why doesn't work for you:
```
.L /myproject/lib/mylib.so
.I /myproject/include/
#include "whatever.h"
```

AFAIK compilation databases are useful when one needs detailed info about the build such as the exact compiler flags. Using cling allows to experiment even with those. Do I miss something?

**Comment by mcraveiro** [comment]
No, I think it's just me missing something :-) I was thinking one could automate that process, but actually its probably quite trivial to write a script that takes a compilation database and converts it into cling commands - e.g. say I want to work with project X; I could simply convert the compilation database for project X into a set of cling commands that sets up cling to experiment with that project. As you say, you probably don't want to directly dump the entire compilation database into cling - most likely we just want to load the SO and load all includes that come with the SO. I shall give it a go at creating a "setup script" that does that.

Many thanks for your time and for the prompt response.

**Comment by vgvassilev** [comment]
Sure, glad to help!
