### ISSUE TITLE
Cling not loading Boost

### ISSUE THREAD

**Issue by nesteruk** [vgvassilev/cling#72]
This may be asking too much, but currently Cling does not load Boost headers, and just crashes.

**Comment by vgvassilev** [comment]
Could you provide move information, please?

**Comment by nesteruk** [comment]
Well, for example you can write #include <boost/asio.hpp> and instead of
loading it, we get an IncrementalExecutor: calling a reserved symbol.

Does loading Boost work for you?


On 24 June 2015 at 00:17, Vassil Vassilev <notifications@github.com> wrote:

> Could you provide move information, please?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vgvassilev/cling/issues/72#issuecomment-114643989>.
>



-- 
Dmitri Nesteruk
dmitrinesteruk@gmail.com
skype: dmitri.nesteruk

**Comment by vgvassilev** [comment]
We haven't done excessive testing. We have tried a few parts and half of them worked half of them didn't. I will have to have a look at this exact issue. Thanks.

**Comment by nesteruk** [comment]
I tried a couple of Boost headers and none of them seem to work. I realize
there's lots of headers being dragged in by every single one, but since
Boost is header-only it's a perfect candidate for this sort of thing.

On 24 June 2015 at 00:26, Vassil Vassilev <notifications@github.com> wrote:

> We haven't done excessive testing. We have tried a few parts and half of
> them worked half of them didn't. I will have to have a look at this exact
> issue. Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vgvassilev/cling/issues/72#issuecomment-114646498>.
>



-- 
Dmitri Nesteruk
dmitrinesteruk@gmail.com
skype: dmitri.nesteruk

**Comment by DiegoAlbertoTorres** [comment]
I have not tried including boost's own headers, but one of my libraries that uses boost works fine. Calling cling as:
 `cling --std=c++11 -I/usr/local/Cellar/boost/1.58.0/include -L/usr/local/Cellar/boost/1.58.0/lib -lboost_system-mt`

**Comment by nesteruk** [comment]
Any updates on this?

**Comment by vgvassilev** [comment]
Yes, it should be fixed by 0.2 release which will happen sometime soon. Sorry for not being very helpful/specific. I hope I can make it by the end of the year.

**Comment by vgvassilev** [comment]
@nesteruk could you retry and reopen if this is still an issue. This should be resolved.
