### ISSUE TITLE
#include<iostream> causes: !DD && Handlers.empty() && "Debug/EH info didn't get finalized"

### ISSUE THREAD

**Issue by zhangxaochen** [vgvassilev/cling#73]
I've successfully built cling on Windows7 with cmake & vs2013. While I was trying to include some cpp headers, the following error occurred:
```
[cling]$ .L iostream
Assertion failed: !DD && Handlers.empty() && "Debug/EH info didn't get finalized", fi
le E:\ABOUT-C++\cling\src\lib\CodeGen\AsmPrinter\AsmPrinter.cpp, line 113
```
![shit](https://cloud.githubusercontent.com/assets/3416677/9976438/df8e61e2-5f16-11e5-9c17-afc14702c3b2.gif)

Am I doing it the wrong way? Or it's a bug of cling with Windows?

**Comment by vgvassilev** [comment]
Thanks for the report. iostream is one of the most complex header files. AFAIK the Windows support of clang (thus cling) is not mature enough to make this work.

**Comment by zhangxaochen** [comment]
@vgvassilev thx for your quick response! So it's not recommended to use cling & clang on Windows right now, right?

**Comment by vgvassilev** [comment]
Exactly, we are not there yet.
