### ISSUE TITLE
CPT Cling Packaging does not build stable release

### ISSUE THREAD

**Issue by mvklingeren** [vgvassilev/cling#74]
Ive tried to build deb packages on Ubuntu 15.10, with the cpt.py --last-stable deb command.

unfortunately, this ended with:

llvm[4]: Compiling CheckEmptyTransactionTransformer.cpp for Release+Asserts build
In file included from /home/mvklingeren/ec/build/cling-src/tools/cling/lib/MetaProcessor/Display.cpp:12:
/home/mvklingeren/ec/build/cling-src/tools/cling/lib/MetaProcessor/../../include/cling/Interpreter/Interpreter.h:15:10: fatal error: 'llvm/ADT/OwningPtr.h' file not found
#include "llvm/ADT/OwningPtr.h"
         ^
In file included from /home/mvklingeren/ec/build/cling-src/tools/cling/lib/Interpreter/CheckEmptyTransactionTransformer.cpp:13:
/home/mvklingeren/ec/build/cling-src/tools/cling/lib/Interpreter/../../include/cling/Interpreter/Transaction.h:18:10: fatal error: 'llvm/ADT/OwningPtr.h' file not found
#include "llvm/ADT/OwningPtr.h"
         ^
1 error generated.
/bin/rm: cannot remove ‘/home/mvklingeren/ec/build/builddir/tools/cling/lib/Interpreter/Release+Asserts/CheckEmptyTransactionTransformer.d.tmp’: No such file or directory
/home/mvklingeren/ec/build/cling-src/Makefile.rules:1519: recipe for target '/home/mvklingeren/ec/build/builddir/tools/cling/lib/Interpreter/Release+Asserts/CheckEmptyTransactionTransformer.o' failed
make[4]: *** [/home/mvklingeren/ec/build/builddir/tools/cling/lib/Interpreter/Release+Asserts/CheckEmptyTransactionTransformer.o] Error 1
make[4]: Leaving directory '/home/mvklingeren/ec/build/builddir/tools/cling/lib/Interpreter'
/home/mvklingeren/ec/build/cling-src/Makefile.rules:937: recipe for target 'Interpreter/.makeall' failed
make[3]: *** [Interpreter/.makeall] Error 2
make[3]: *** Waiting for unfinished jobs....
llvm[4]: Compiling InputValidator.cpp for Release+Asserts build
1 error generated.
/bin/rm: cannot remove ‘/home/mvklingeren/ec/build/builddir/tools/cling/lib/MetaProcessor/Release+Asserts/Display.d.tmp’: No such file or directory
/home/mvklingeren/ec/build/cling-src/Makefile.rules:1519: recipe for target '/home/mvklingeren/ec/build/builddir/tools/cling/lib/MetaProcessor/Release+Asserts/Display.o' failed
make[4]: *** [/home/mvklingeren/ec/build/builddir/tools/cling/lib/MetaProcessor/Release+Asserts/Display.o] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: Leaving directory '/home/mvklingeren/ec/build/builddir/tools/cling/lib/MetaProcessor'
/home/mvklingeren/ec/build/cling-src/Makefile.rules:937: recipe for target 'MetaProcessor/.makeall' failed
make[3]: *** [MetaProcessor/.makeall] Error 2
make[3]: Leaving directory '/home/mvklingeren/ec/build/builddir/tools/cling/lib'
/home/mvklingeren/ec/build/cling-src/Makefile.rules:878: recipe for target 'all' failed
make[2]: *** [all] Error 1
make[2]: Leaving directory '/home/mvklingeren/ec/build/builddir/tools/cling'
/home/mvklingeren/ec/build/cling-src/Makefile.rules:963: recipe for target 'all' failed
make[1]: *** [all] Error 1
make[1]: Leaving directory '/home/mvklingeren/ec/build/builddir/tools'
/home/mvklingeren/ec/build/cling-src/Makefile.rules:878: recipe for target 'all' failed
make: *** [all] Error 1
subprocess.CalledProcessError: Command 'make -j2' returned non-zero exit status 2
 
 
 
┌──────────────────────────────────────────────────────────────────────────────┐
│ Clean up                                                                     │
└──────────────────────────────────────────────────────────────────────────────┘
Remove directory: /home/mvklingeren/ec/build/builddir
Remove directory: /tmp/cling-obj/
Create output directory: /home/mvklingeren/ec/build/cling-0.1-1

**Comment by vgvassilev** [comment]
@onyb could you help us out?

**Comment by mvklingeren** [comment]
I checked the latest-dev source file Interpreter.h, that does not seem to have a reference to:
'llvm/ADT/OwningPtr.h'

But its still compiling the dev build now, not sure if that will build; but stable should just work with CPT ..

What i think is the problem, there is no llvm directory in the tools directory, and there is no ADT, OwingPtr.h either (that file is not in my build dir, checked with grep), so there is something missing.

**Comment by mvklingeren** [comment]
And the result of an attempt to build the latest-dev, resulted in a signing error (i do not have Cling CERN signing keys..):


Now running lintian...
E: cling changes: bad-distribution-in-changes-file unstable
Use of uninitialized value $maintainer in substitution (s///) at /usr/share/lintian/checks/nmu.pm line 135.
Use of uninitialized value $uploader in string ne at /usr/share/lintian/checks/nmu.pm line 98.
W: cling: hardening-no-relro usr/bin/cling
W: cling: syntax-error-in-debian-changelog line 801 "badly formatted trailer line"
W: cling: syntax-error-in-debian-changelog line 6017 "found eof where expected more change data or trailer"
W: cling: new-package-should-close-itp-bug
W: cling: spelling-error-in-changelog Reenable Re-enable
W: cling: spelling-error-in-changelog compatiblity compatibility
N: 1 tag overridden (1 error)
Finished running lintian.
Now signing changes and any dsc files...
 signfile cling_0.2~dev-2d27a56-1.dsc Cling Developer Team <cling-dev@cern.ch>
gpg: keyring `/home/mvklingeren/.gnupg/secring.gpg' created
gpg: skipped "Cling Developer Team <cling-dev@cern.ch>": secret key not available
gpg: /tmp/debsign.G5IBxVt8/cling_0.2~dev-2d27a56-1.dsc: clearsign failed: secret key not available
debsign: gpg error occurred!  Aborting....
debuild: fatal error at line 1293:
running debsign failed
subprocess.CalledProcessError: Command 'debuild' returned non-zero exit status 29



┌──────────────────────────────────────────────────────────────────────────────┐
│ Clean up                                                                     │
└──────────────────────────────────────────────────────────────────────────────┘
Remove directory: /home/mvklingeren/ec/build/builddir
Remove directory: /home/mvklingeren/ec/build/cling-0.2~dev-2d27a56
Remove directory: /tmp/cling-obj/


Help...?

**Comment by onyb** [comment]
@mvklingerenl : Unfortunately ```v0.1``` is not actually "stable", and was tagged a long time ago. There has been with lot of development activity both in Cling as well as LLVM since then, and the current ```cling-patches``` branch of LLVM is not compatible with Cling at the tag ```v0.1```. I will write a fix for this, but do not consider ```v0.1``` as a stable release.

This repository on GitHub hasn't been updated in a while. The original repository is [here](https://root.cern.ch/gitweb?p=cling.git;a=shortlog), and is used as the default Cling by CPT, unless you tell it to use a different Git repository with the ```--with-cling-url``` option. The master branch of the original repository should build successfully, with one failing test case. You might want to suppress running of the Cling test cases altogether with ```--no-test``` option for now. We will tag a new version soon, after which you won't have to do this.

@vgvassilev : Could you update this GitHub repo? Also there are a few commits here (including CPT patches) which haven't been committed to the original repo.

Finally coming to the Debian packages, you don't need CERN keys to sign your package. The original idea was that any user can build his/her own packages, sign it himself, and distribute it as an authentic package. My guess is that you don't have GPG keys set up on your machine. To confirm, enter ```gpg --fingerprint``` on your Linux terminal. If you don't see any output, then something is wrong. Check the [CPT documentation](https://github.com/vgvassilev/cling/blob/master/tools/packaging/README.md) for help.

**Comment by vgvassilev** [comment]
@onyb Should be done now. Could you check whether this is still an issue and if not close the ticket?

**Comment by vgvassilev** [comment]
Should be fixed.
