### ISSUE TITLE
make install doesn't work on Mac OS El Capitan

### ISSUE THREAD

**Issue by projetmbc** [vgvassilev/cling#78]
make install gives me the following error message.

    /Users/xxxx/cling/src/include/llvm/ADT/StringRef.h:13:10: fatal error: 
      'algorithm' file not found
    #include <algorithm>
             ^
    1 error generated.

**Comment by vgvassilev** [comment]
We are working on it.

**Comment by projetmbc** [comment]
Thanks for this !

**Comment by vgvassilev** [comment]
Sorry for the late answer. The issue should be fixed. Please reopen if you still have the same issue.
