### ISSUE TITLE
Replace the LLVM module jit by mcjit

### ISSUE THREAD

**Issue by remysaissy** [vgvassilev/cling#79]
The jit module will be removed and is replaced by mcjit in llvm > 3.5.
I'm trying to build an homebrew formula for cling and I ran into the issue that llvm 3.6.x (provided in homebrew) no longer has the jit module. Instead it has moved to the new mcjit.

http://blog.llvm.org/2013/07/using-mcjit-with-kaleidoscope-tutorial.html

**Comment by vgvassilev** [comment]
Thanks for the suggestion. MCJIT is not quite what we need for cling. We ended up replacing cling's JIT with OrcJIT (starting from v0.2).
