### ISSUE TITLE
The binary snapshot download page (https://ecsft.cern.ch/dist/cling) is broken.

### ISSUE THREAD

**Issue by svetlin-mladenov** [vgvassilev/cling#80]
The SSL certificate is invalid (domains don't match) and even if this error is ignored the server returns 404 not found.

**Comment by onyb** [comment]
This looks like a problem with Electric Commander, since I cannot access the login page. The parent directory `/dist` contains only `cvmfs` and `cernvm`, and no `cling`.

**Comment by vgvassilev** [comment]
Yes, we have turbulence in our infrastructure since we are moving to jenkins. That issue should be addressed soon.

**Comment by vgvassilev** [comment]
@onyb this is one of the reasons I want to have build/release infrastructure running on github. And I am looking forward to your future PR ;)

**Comment by palxex** [comment]
Any update?

**Comment by vgvassilev** [comment]
Yes, we are almost there. We are waiting for our IT department to allow jenkins to connect to github. Sorry sometimes things are slower than I'd wish for.

**Comment by onyb** [comment]
@palxex : You can find the latest Cling release on my GitHub fork: https://github.com/onyb/cling/releases. Please note that it is a pre-release.

@vgvassilev: We need to update the `master` branch, and sync it with the original [repository](https://root.cern.ch/gitweb?p=cling.git;a=shortlog). Once that is done, we can merge in the commits from my fork. You can see my changeset [here](https://github.com/vgvassilev/cling/compare/master...onyb:cpt).

**Comment by palxex** [comment]
@onyb Great! Thanks.

**Comment by alefpereira** [comment]
@onyb Thank you!

**Comment by CMCDragonkai** [comment]
https://root.cern.ch/download/cling/ ?

**Comment by vgvassilev** [comment]
The intent to be mirrors. However the development diverged. It is on my todo list to sync all changes in both repos.
