### ISSUE TITLE
Build process (as described in README.md) not working

### ISSUE THREAD

**Issue by forflo** [vgvassilev/cling#85]
Hi,

I'm trying to build cling from source using exactly the method
you described in the README.md of this repository. I'd rather
like to download ready-to-play binaries, but I read, that's not
possible right now because of your infrastructure refactoring.

I also tried to build the package using [this](https://raw.githubusercontent.com/karies/cling-all-in-one/master/clone.sh) build script that is linked also in the
documentation. No success either. CMake threw a very
strange error claiming that a "SetTheory" Module might be
missing or simply corrupt(?). Then I tried to use [onyb's](https://github.com/onyb/cling/releases)
uploaded binaries, but since they've been build specifically for Ubuntu, I can't
run them, because I'm currently running Arch.

My CMake version is 3.4.3

Am I missing an obvious step?
Could you update your build instructions?

**Comment by maddouri** [comment]
I've had a similar problem on my Ubuntu 16.04. So I decided to compile it inside a Docker container running Ubuntu 14.04. Seems to work well :)

Feel free to have a look at [my repo](https://github.com/maddouri/cling-ubuntu-docker) or directly get the build by executing `docker pull maddouri/cling-ubuntu-docker`.

One interesting side-effect of this approach is that it should be possible to use this same image on any machine running docker. Just `docker pull` & play!

**Comment by vgvassilev** [comment]
Ah, really cool! Could you contribute the config back? I'd love to see vagrant too ;)

**Comment by maddouri** [comment]
Thanks!

Sure. I'll prepare a pull request.

**Comment by forflo** [comment]
Thanks!

**Comment by vgvassilev** [comment]
This should be fixed.
