### ISSUE TITLE
Interactive interpreter does not exit on EOF

### ISSUE THREAD

**Issue by tforgione** [vgvassilev/cling#86]
On linux, when you're on a terminal, you can use `Ctrl+D` to send EOF to the program.

For example, in python, typing `Ctrl+D` in the terminal exits the interpreter.

The following snippet also exists on EOF.

``` cpp
#include <iostream>
#include <string>

int main(int argc, char *argv[])
{
    std::string str;

    while (std::getline(std::cin, str))
        std::cout << "You typed : " << str << std::endl;

    return 0;
}
```

Is there a reason why `cling` ignores my `Ctrl+D` ?

**Comment by vgvassilev** [comment]
You can exit with `.q`. Ctrl+D is not implemented.

**Comment by tforgione** [comment]
I see, thanks.

I just wanted to know if it was expected behavior or something like this.

**Comment by vgvassilev** [comment]
We never had Ctrl+D user requests and thus we didn't find it necessary to implement it.
