### ISSUE TITLE
Tab auto-complete

### ISSUE THREAD

**Issue by Manouchehri** [vgvassilev/cling#89]
It would be neat feature if Cling used Clang's auto-completion in the REPL.

http://clang.llvm.org/doxygen/group__CINDEX__CODE__COMPLET.html

**Comment by vgvassilev** [comment]
I agree, there has been work in that area and I hope it will converge soon.

**Comment by Manouchehri** [comment]
@vgvassilev I think Clang already has everything done, there's more work to be done in Cling though. =)

**Comment by ax3l** [comment]
@vgvassilev is there anyone still working on code completion?

**Comment by vgvassilev** [comment]
Cling code completion should work. Just press tab for seeing the autocomplete options.

**Comment by ax3l** [comment]
Oh :)

I just tried
```C++
#include <vector>

std::vector<int> v(10, 3);
v.<TAB>
```

and got no completion on a ~3 week old `0.4~dev` version :(

**Comment by vgvassilev** [comment]
Ah, please go ahead and open a new issue for this.

**Comment by ax3l** [comment]
Thanks, moved to #121

**Comment by Manouchehri** [comment]
Using Jupyter might be a better idea if possible.

**Comment by dabro** [comment]
I didn’t know tab completion for Cling worked in Jupyter?
