### ISSUE TITLE
Warning when starting up on Ubuntu 16

### ISSUE THREAD

**Issue by nesteruk** [vgvassilev/cling#93]
When firing up latest binary snapshot, I get:

```
Warning in cling::IncrementalParser::CheckABICompatibility():
C++ ABI mismatch, compiled with __GLIBCXX__ v20160413 running with v20160609
```

**Comment by vgvassilev** [comment]
Could you tell us on which platform and which binary shapshot are you using?

**Comment by nesteruk** [comment]
It's Ubuntu Desktop 16.04 64-bit, and the binary snapshot is the latest one
you can get right now.

On 14 July 2016 at 09:16, Vassil Vassilev <notifications@github.com> wrote:

> Could you tell us on which platform and which binary shapshot are you
> using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/vgvassilev/cling/issues/93#issuecomment-232566374>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAcoNuTCAMlTRJ5s78f7NBKvEXHctHqVks5qVdRYgaJpZM4JL3x2>
> .
>



-- 
Dmitri Nesteruk
dmitrinesteruk@gmail.com
skype: dmitri.nesteruk

**Comment by vgvassilev** [comment]
The issues with the ABI compatibility were recently fixed. Please retry and reopen if this is still an issue.

**Comment by hacst** [comment]
Still seing the very same message with my fully updated Ubuntu 16.04.1 LTS and the cling_2016-09-14_ubuntu16 snapshot.

```
Warning in cling::IncrementalParser::CheckABICompatibility():
  C++ ABI mismatch, compiled with __GLIBCXX__ v20160413 running with v20160609
```

**Comment by vgvassilev** [comment]
IIUC @karies plans to disable this check.

**Comment by vgvassilev** [comment]
We did some progress on this and I believe the issue is gone. Please reopen if you still see this.
