### ISSUE TITLE
How to configure jupyter-cling-kernel to use std=c++11?

### ISSUE THREAD

**Issue by adamryczkowski** [vgvassilev/cling#95]
I checked `jupyter-cling-kernel --help` but I failed to find any command line switch to pass arguments to cling. Can anyone help me? 

I am setting up C++ kernel for Jupyter. I want students to be able to use iostream library - but this requires c++11 compatibility, which is not by default. 

I use headless Ubuntu 16.04 server.

**Comment by vgvassilev** [comment]
You can pass arguments to cling in the same way as to any compiler: `cling -x c++ -std=c++11`. Does that help?

**Comment by adamryczkowski** [comment]
@vgvassilev Thank you for your answer. Jupyter uses `jupyter-cling-kernel` so I need to pass there, not to `cling`. I'll try to use these arguments to it nevertheless, maybe they will get forwarded to cling. I'll post the result.

**Comment by vgvassilev** [comment]
@karies should be able to help, he is the original implementer of this part.

**Comment by karies** [comment]
C++11 is enabled automatically as soon as cling is built with C++11. That's needed because cling resolves some symbols from its own binaries, so runtime and compile ABI must match. Makes sense?

**Comment by adamryczkowski** [comment]
@karies Thank you. It does make sense. The question is: what is the preferred way to build it using C++11 standard. Should I edit some cmake files, or is there any command line switch for this occasion?

**Comment by karies** [comment]
As you are building cling "as part of" llvm you'll want to configure llvm to build with C++11. And that's actually a requirement these days. I.e. your cling /is/ already built with C++11 unless you configured your llvm / clang / cling build to use C++14 yourself.

**Comment by adamryczkowski** [comment]
@karies  Well, I don't think so. I just (3 days ago) have manually compiled the cling on the most recent Ubuntu 16.04 and the jupyter-cling-kernel doesn't let me use 

```
#inculde<iostream>
std::count<<"Hello world!\n";
```

Cling also doesn't allow it, but it can be easily fixed by adding --std=c++11 command line parameter. 

I just want to know, how to modify the `.local/share/jupyter/kernels/cling.json` so the `jupyter-cling-kernel` would let me use `iostream` standard templates.

**Comment by karies** [comment]
Until we have implemented the separation of declarations and statements within one piece of input you'll have to do
```
#include <iostream>
```
in one cell, and
```
std::cout << "Hello world\n";
```
in the next. Note that you misspelled `cout`. And also - this has nothing to do with C++11. You can test for the C++ version in use by evaluating the preprocessor macro
```
__cplusplus
```

**Comment by adamryczkowski** [comment]
YES, it works! How stupid of me. Now I even remember reading somewhere about this limitation of the cling kernel... I'm sorry for taking your time. 

And by the way, thank you for developing such wonderful tool.

**Comment by karies** [comment]
No problem - this /is/ annoying, and I really do want to have this fixed. Thanks for the flowers, though :-) Enjoy!

**Comment by wwwillchen** [comment]
Sorry to stir up an old issue. Has the issue around the separation of declarations and statements within one piece of input been fixed? I'm experiencing the same issue but I don't quite understand why the #include statements need to be in a separate preceding cell.
