### ISSUE TITLE
build and install them using CMake

### ISSUE THREAD

**Issue by lSODAMl** [vgvassilev/cling#97]
I want to install cling and I used CMake.
I make build directory and I type in cmd that 'cmake -DCMAKE_INSTALL_PREFIX=c:\cling\src
But there is an error. 'C:/cling/build' does not appear to contain CMakeLists.txt.
One more. when I type cmd 'make' and 'make install, cmd said make and make install is not recognized as an internal or external command, operable program or batch file. 
What can I do?

**Comment by onyb** [comment]
I would create a build directory, `cd` into it, and then do something like this:

```sh
cmake -DLLVM_ENABLE_LIBCXX=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=<install dir> <src dir>
```
Please check out the [packaging tool](https://github.com/vgvassilev/cling/tree/master/tools/packaging), which is generally an easier way to build Cling.

**Comment by lSODAMl** [comment]
What is <intall dir>?
Is it specific dir or not related other dir?

**Comment by onyb** [comment]
I guess you meant the build directory. You can name it anything and put it in any location, but prefer keeping it out of the source tree.

**Comment by lSODAMl** [comment]
Thanks! 
On GNU Make
../src/configure --prefix=/some/install/dir
'../' this command is cmd command?
In my cmd, it is not recognized as an internal or external command, operable program or batch file.

**Comment by onyb** [comment]
LLVM has dropped support for `configure` based builds, in favor of CMake. You should use CMake directly, or use the packaging scripts I pointed you to.
