### ISSUE TITLE
Exception recovery is inconsistent

### ISSUE THREAD

**Issue by nesteruk** [vgvassilev/cling#99]
Why does `0/0` work, `throw 3` also lets Cling recover, but writing `int x = 3; x/(x-x)` crash Cling?

**Comment by vgvassilev** [comment]
@CristinaCristescu do you have an idea what is going wrong here?

**Comment by vgvassilev** [comment]
0/0 is easily detectable because of the constant values. When we have complicated expressions we cannot statically reason about the code. Of course we need to figure out how to protect cling from crashing there.
